# Test Environment State Specification
# This demonstrates declarative state management for tests

state:
  # Document requirements
  document_count: 100
  document_source: "data/sample_10_docs"
  document_selection:
    strategy: "first_n"  # Take first N documents
    criteria:
      min_length: 100
      has_abstract: true
  
  # Embedding configuration
  embedding_model: "all-MiniLM-L6-v2"
  embedding_dimension: 384
  force_regenerate: false  # Only regenerate if needed
  
  # Quality requirements
  min_embedding_diversity: 0.1  # Relaxed for test data
  max_contamination_ratio: 0.05  # Allow some mocks in tests
  validation_mode: "lenient"  # More forgiving for tests
  
  # Pipeline configuration
  pipeline_type: "basic"
  chunk_size: 512
  chunk_overlap: 50

# Reconciliation settings for this state
reconciliation:
  auto_retry: true
  max_retries: 3
  convergence_timeout: 300  # 5 minutes
  
# Test-specific settings
test:
  preserve_on_failure: true
  isolate_tables: true
  cleanup_after: true