# Extended Quick Start configuration
# Full-featured setup with 1000 documents and all RAG techniques

extends: "quick_start"

metadata:
  profile: "quick_start_extended"
  description: "Extended quick start with 1000 documents and all RAG techniques"

sample_data:
  document_count: 1000
  categories: ["medical", "biomedical", "clinical", "research"]
  parallel_downloads: 8
  batch_size: 50

performance:
  batch_size: 32
  max_workers: 4

mcp_server:
  tools:
    enabled:
      - "rag_basic"
      - "rag_crag"
      - "rag_hyde"
      - "rag_graphrag"
      - "rag_hybrid_ifind"
      - "rag_colbert"
      - "rag_noderag"
      - "rag_sqlrag"
      - "rag_health_check"
      - "rag_list_techniques"
      - "rag_performance_metrics"

monitoring:
  enabled: true
  dashboard:
    enabled: true
    port: 8080
  health_checks:
    enabled: true
    interval: 30

documentation:
  server:
    enabled: true
    port: 8081