# Quick Start configuration template
# Optimized for IRIS Community Edition and quick onboarding

extends: "base_config"

metadata:
  profile: "quick_start"
  description: "Quick start configuration optimized for community edition"

# Override database settings for community edition
database:
  iris:
    connection_pool:
      min_connections: 1
      max_connections: 5
      connection_timeout: 15

# Quick start specific storage settings
storage:
  iris:
    table_name: "QuickStart.Documents"
    vector_dimension: 384
  
  chunking:
    chunk_size: 256  # Smaller chunks for quick start
    overlap: 25

# Sample data configuration
sample_data:
  enabled: true
  auto_download: true
  source_type: "pmc_api"
  storage_path: "data/quick_start_samples"
  cache_enabled: true
  cleanup_on_success: false

# MCP Server configuration
mcp_server:
  enabled: true
  name: "rag-quick-start"
  description: "RAG Templates Quick Start Server"
  port: "${MCP_SERVER_PORT:-3000}"
  auto_start: true
  demo_mode: true
  
  tools:
    enabled:
      - "rag_basic"
      - "rag_hyde"
      - "rag_crag"
      - "rag_graphrag"
      - "rag_colbert"
      - "rag_noderag"
      - "rag_hybrid_ifind"
      - "rag_sqlrag"
      - "rag_health_check"

# Performance optimized for quick start
performance:
  batch_size: 16  # Smaller batches
  max_workers: 2  # Fewer workers
  timeout: 15
  cache:
    enabled: true
    ttl: 1800  # Shorter TTL
    max_size: 500

# Monitoring configuration
monitoring:
  enabled: true
  metrics:
    enabled: true
    port: "${METRICS_PORT:-9090}"
  health_checks:
    enabled: true
    interval: 30
  
# Documentation server
docs_server:
  enabled: true
  port: "${DOCS_PORT:-8080}"
  auto_generate: true