# Demo Quick Start configuration
# Showcase profile with demo applications, migration examples, and MCP server

extends: "quick_start"

metadata:
  profile: "quick_start_demo"
  description: "Demo showcase with chat app, migration examples, and MCP server"
  version: "1.0.0"
  target_audience: "developers, evaluators, customers"
  use_cases: 
    - "Framework migration demonstrations"
    - "Interactive chat application"
    - "MCP server integration"
    - "ObjectScript integration examples"
    - "Performance comparisons"

sample_data:
  document_count: 50
  categories: ["medical", "biomedical", "ai_research"]
  parallel_downloads: 2
  batch_size: 10
  include_demo_datasets: true
  demo_datasets:
    - name: "healthcare_sample"
      type: "structured"
      records: 25
      description: "Sample patient data for IRIS integration demos"
    - name: "research_papers"
      type: "documents"
      count: 15
      description: "AI/ML research papers for technique comparisons"
    - name: "migration_examples"
      type: "code_samples"
      frameworks: ["langchain", "llamaindex", "custom"]
      description: "Code examples for migration demonstrations"

performance:
  batch_size: 8
  max_workers: 1
  optimize_for: "demonstration"
  enable_metrics: true
  track_performance: true

# Demo Chat Application Configuration
demo_chat_app:
  enabled: true
  features:
    simple_api: true
    standard_api: true
    enterprise_api: true
    conversation_history: true
    technique_comparison: true
    migration_demos: true
    objectscript_integration: true
  web_interface:
    enabled: true
    port: 8080
    host: "localhost"
  cli_interface:
    enabled: true
    interactive_mode: true

# MCP Server Configuration
mcp_server:
  enabled: true
  port: 3000
  tools:
    enabled:
      - "rag_basic"
      - "rag_hyde" 
      - "rag_crag"
      - "rag_colbert"
      - "rag_graphrag"
      - "rag_hybrid_ifind"
      - "rag_noderag"
      - "rag_sql_rag"
      - "rag_health_check"
      - "rag_list_techniques"
      - "rag_technique_compare"
      - "demo_migration_langchain"
      - "demo_migration_llamaindex"
      - "demo_objectscript_integration"
      - "demo_performance_benchmark"
      - "document_management"
      - "iris_data_integration"
  authentication:
    enabled: false  # Demo mode
  logging:
    level: "INFO"
    track_usage: true

# Migration Demo Configuration
migration_demos:
  enabled: true
  frameworks:
    langchain:
      enabled: true
      examples:
        - "basic_rag"
        - "conversational_rag"
        - "document_loading"
        - "custom_embeddings"
    llamaindex:
      enabled: true
      examples:
        - "simple_index"
        - "query_engine"
        - "chat_engine"
        - "custom_retriever"
    custom:
      enabled: true
      examples:
        - "manual_embeddings"
        - "vector_search"
        - "llm_integration"
  comparison_metrics:
    - "lines_of_code"
    - "setup_time"
    - "performance"
    - "maintainability"

# ObjectScript Integration
objectscript_integration:
  enabled: true
  examples:
    - name: "basic_rag_call"
      description: "Call RAG from ObjectScript"
      type: "class_method"
    - name: "patient_insight_query"
      description: "Healthcare-specific RAG integration"
      type: "business_logic"
    - name: "batch_processing"
      description: "Bulk document processing"
      type: "data_processing"
  mcp_bridge:
    enabled: true
    functions:
      - "invoke_rag_basic_mcp"
      - "invoke_rag_crag_mcp"
      - "invoke_rag_hyde_mcp"
      - "get_mcp_health_status"

# IRIS Integration Demos
iris_integration:
  enabled: true
  existing_data_demo:
    enabled: true
    sample_tables:
      - table: "Demo.Patient"
        content_fields: ["FirstName", "LastName", "Diagnosis", "Notes"]
        id_field: "PatientID"
        template: "Patient {FirstName} {LastName}: {Diagnosis}. Notes: {Notes}"
      - table: "Demo.Research"
        content_fields: ["Title", "Abstract", "Authors"]
        id_field: "PaperID"
        template: "Research: {Title} by {Authors}. Abstract: {Abstract}"
  embedded_python:
    enabled: true
    examples:
      - "direct_iris_sql"
      - "performance_optimization"
      - "bulk_operations"
  wsgi_deployment:
    enabled: true
    demo_endpoints:
      - "/chat"
      - "/migrate" 
      - "/compare"
      - "/objectscript"

# Tutorial System
interactive_tutorial:
  enabled: true
  steps:
    - name: "simple_api_intro"
      description: "Learn the Simple API"
      duration: "5 minutes"
    - name: "standard_api_features"
      description: "Explore Standard API configuration"
      duration: "10 minutes"
    - name: "enterprise_techniques"
      description: "Advanced RAG techniques"
      duration: "15 minutes"
    - name: "migration_demo"
      description: "See framework migration"
      duration: "10 minutes"
    - name: "iris_integration"
      description: "IRIS-specific features"
      duration: "15 minutes"
    - name: "mcp_server_usage"
      description: "Use MCP server tools"
      duration: "10 minutes"

# Monitoring and Metrics
monitoring:
  enabled: true
  track_demo_usage: true
  performance_metrics: true
  user_interactions: true
  export_format: "json"

# Environment Setup
environment:
  python_packages:
    - "flask>=2.0.0"
    - "websockets>=10.0"
    - "plotly>=5.0.0"  # For performance visualizations
  demo_data_size: "small"  # Keep demo lightweight
  cleanup_on_exit: true