openapi: 3.0.3
info:
  title: HippoRAG Pipeline Contract
  description: |
    API contract for the HippoRAGPipeline class implementing the RAGPipeline interface.

    This contract defines the standardized methods, request/response formats, and
    behavior requirements for the HippoRAG2 pipeline integration.
  version: 1.0.0

components:
  schemas:
    Document:
      type: object
      description: LangChain Document object
      required:
        - page_content
      properties:
        id:
          type: string
          description: Unique document identifier
        page_content:
          type: string
          description: Document text content
        metadata:
          type: object
          description: Document metadata
          additionalProperties: true

    QueryRequest:
      type: object
      required:
        - query_text
      properties:
        query_text:
          type: string
          description: Natural language query
          example: "What county is Erik Hort's birthplace a part of?"
        top_k:
          type: integer
          description: Number of passages to retrieve
          default: 20
          minimum: 1
          maximum: 100
        include_sources:
          type: boolean
          description: Include source references in response
          default: true
        generate_answer:
          type: boolean
          description: Generate LLM answer (if false, retrieval only)
          default: true
        custom_prompt:
          type: string
          description: Custom LLM prompt template
          nullable: true

    QueryResponse:
      type: object
      required:
        - query
        - answer
        - retrieved_documents
        - contexts
        - sources
        - execution_time
        - metadata
      properties:
        query:
          type: string
          description: Original query text
        answer:
          type: string
          description: Generated answer (or null if generate_answer=false)
          nullable: true
        retrieved_documents:
          type: array
          description: Retrieved documents with full metadata
          items:
            $ref: '#/components/schemas/Document'
        contexts:
          type: array
          description: Text content of retrieved passages (for RAGAS evaluation)
          items:
            type: string
        sources:
          type: array
          description: Source references with metadata
          items:
            $ref: '#/components/schemas/SourceReference'
        execution_time:
          type: number
          format: double
          description: Total execution time in seconds
        metadata:
          $ref: '#/components/schemas/ResponseMetadata'

    SourceReference:
      type: object
      required:
        - document_id
        - source
        - retrieval_method
      properties:
        document_id:
          type: string
          description: Document identifier
        source:
          type: string
          description: Source file path or URL
        title:
          type: string
          description: Document title
        retrieval_method:
          type: string
          description: How this document was retrieved
          enum:
            - entity_linking
            - graph_traversal
            - vector_search
            - hybrid

    ResponseMetadata:
      type: object
      required:
        - num_retrieved
        - pipeline_type
        - generated_answer
        - processing_time
        - retrieval_method
        - context_count
      properties:
        num_retrieved:
          type: integer
          description: Number of documents retrieved
        pipeline_type:
          type: string
          const: hipporag
        generated_answer:
          type: boolean
          description: Whether LLM answer was generated
        processing_time:
          type: number
          format: double
          description: Total processing time in seconds (same as execution_time)
        retrieval_method:
          type: string
          description: Primary retrieval method used
        context_count:
          type: integer
          description: Number of contexts returned
        entity_linking_time:
          type: number
          format: double
          description: Time spent on entity linking (ms)
        graph_traversal_time:
          type: number
          format: double
          description: Time spent on graph traversal (ms)
        passage_retrieval_time:
          type: number
          format: double
          description: Time spent on passage retrieval (ms)
        llm_generation_time:
          type: number
          format: double
          description: Time spent on LLM generation (ms)
        entities_extracted:
          type: integer
          description: Number of entities extracted from query
        graph_hops:
          type: integer
          description: Number of graph hops traversed

    LoadDocumentsRequest:
      type: object
      required:
        - documents_path
      properties:
        documents_path:
          type: string
          description: Path to documents directory or file
        documents:
          type: array
          description: List of Document objects (alternative to documents_path)
          items:
            $ref: '#/components/schemas/Document'
          nullable: true
        generate_embeddings:
          type: boolean
          description: Generate embeddings during indexing
          default: true
        extract_entities:
          type: boolean
          description: Extract entities and build knowledge graph
          default: true
        chunk_size:
          type: integer
          description: Chunk size for document splitting
          default: 512
          minimum: 128
          maximum: 2048

    LoadDocumentsResponse:
      type: object
      required:
        - documents_indexed
        - chunks_created
        - entities_extracted
        - relationships_extracted
        - indexing_time
      properties:
        documents_indexed:
          type: integer
          description: Number of documents successfully indexed
        chunks_created:
          type: integer
          description: Number of chunks created
        entities_extracted:
          type: integer
          description: Number of unique entities extracted
        relationships_extracted:
          type: integer
          description: Number of relationships extracted
        indexing_time:
          type: number
          format: double
          description: Total indexing time in seconds
        errors:
          type: array
          description: List of errors encountered
          items:
            type: string

paths:
  /pipeline/query:
    post:
      summary: Execute HippoRAG query
      description: |
        Perform multi-hop reasoning query using knowledge graph traversal and
        associative retrieval. Returns standardized RAG response.
      operationId: query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful query execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request (empty query, invalid top_k, etc.)
        '500':
          description: Server error (LLM failure, IRIS connection error, etc.)

  /pipeline/load_documents:
    post:
      summary: Index documents into HippoRAG
      description: |
        Load documents, extract entities/relationships, build knowledge graph,
        and generate embeddings. Supports incremental indexing.
      operationId: load_documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoadDocumentsRequest'
      responses:
        '200':
          description: Documents successfully indexed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoadDocumentsResponse'
        '400':
          description: Invalid request (empty documents, invalid path, etc.)
        '500':
          description: Server error (OpenIE failure, IRIS error, etc.)

  /pipeline/retrieve:
    post:
      summary: Retrieve passages only (no answer generation)
      description: |
        Perform retrieval without LLM answer generation. Returns ranked passages.
      operationId: retrieve
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query_text
              properties:
                query_text:
                  type: string
                top_k:
                  type: integer
                  default: 20
      responses:
        '200':
          description: Retrieved passages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'

  /pipeline/ask:
    post:
      summary: Get answer only (simplified query interface)
      description: |
        Simplified interface that returns only the generated answer string.
      operationId: ask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
              properties:
                question:
                  type: string
      responses:
        '200':
          description: Generated answer
          content:
            text/plain:
              schema:
                type: string

  /pipeline/health:
    get:
      summary: Health check
      description: |
        Verify pipeline is ready for queries. Checks:
        - IRIS connection
        - iris-vector-graph tables exist
        - Knowledge graph is populated
        - LLM is accessible
      operationId: health_check
      responses:
        '200':
          description: Pipeline is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy, degraded, unhealthy]
                  checks:
                    type: object
                    properties:
                      iris_connection:
                        type: boolean
                      tables_exist:
                        type: boolean
                      graph_populated:
                        type: boolean
                      llm_accessible:
                        type: boolean
                  entities_count:
                    type: integer
                  relationships_count:
                    type: integer
        '503':
          description: Pipeline is unhealthy

# Contract Test Requirements
x-contract-tests:
  query:
    - name: test_query_returns_standard_format
      description: Verify response has all required fields (answer, retrieved_documents, contexts, etc.)
      assertions:
        - response.answer is not None
        - len(response.retrieved_documents) > 0
        - len(response.contexts) > 0
        - response.metadata.pipeline_type == "hipporag"

    - name: test_query_multi_hop_reasoning
      description: Verify multi-hop query "What county is Erik Hort's birthplace a part of?" works
      query: "What county is Erik Hort's birthplace a part of?"
      assertions:
        - "Rockland County" in response.answer
        - len(response.metadata.entities_extracted) >= 3
        - response.metadata.graph_hops >= 2

    - name: test_query_backward_compatibility
      description: Verify deprecated query_text parameter still works
      query_text: "Test query"  # Should work (aliased to query)
      assertions:
        - response.query == "Test query"

  load_documents:
    - name: test_load_documents_incremental
      description: Verify incremental indexing works (add documents without full rebuild)
      steps:
        - Index 5 documents
        - Verify 5 documents indexed
        - Index 3 more documents
        - Verify 8 total documents indexed
        - Verify no duplicate entities

    - name: test_load_documents_entity_extraction
      description: Verify entities and relationships are extracted
      assertions:
        - response.entities_extracted > 0
        - response.relationships_extracted > 0

  retrieve:
    - name: test_retrieve_returns_documents
      description: Verify retrieve returns Document objects
      assertions:
        - len(results) > 0
        - all(hasattr(doc, 'page_content') for doc in results)
        - all(hasattr(doc, 'metadata') for doc in results)

  health_check:
    - name: test_health_check_validates_requirements
      description: Verify health check detects missing requirements
      assertions:
        - checks.iris_connection == True
        - checks.tables_exist == True
        - checks.graph_populated == True
