openapi: 3.0.0
info:
  title: Quality Gate API
  version: 1.0.0
  description: API for CI/CD quality gate evaluation

paths:
  /quality-gates/evaluate:
    post:
      summary: Evaluate all quality gates for a build
      operationId: evaluateQualityGates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - build_id
                - test_results
                - coverage_report
              properties:
                build_id:
                  type: string
                test_results:
                  $ref: '#/components/schemas/TestResults'
                coverage_report:
                  $ref: '#/components/schemas/CoverageReport'
                performance_metrics:
                  $ref: '#/components/schemas/PerformanceMetrics'
      responses:
        '200':
          description: Quality gates evaluated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityGateResult'

  /quality-gates/status/{build_id}:
    get:
      summary: Get quality gate status for a build
      operationId: getQualityGateStatus
      parameters:
        - name: build_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Quality gate status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QualityGateResult'
        '404':
          description: Build not found

components:
  schemas:
    TestResults:
      type: object
      required:
        - total_tests
        - passed_tests
        - failed_tests
        - skipped_tests
      properties:
        total_tests:
          type: integer
          minimum: 0
        passed_tests:
          type: integer
          minimum: 0
        failed_tests:
          type: integer
          minimum: 0
        skipped_tests:
          type: integer
          minimum: 0
        error_tests:
          type: integer
          minimum: 0
        execution_time_seconds:
          type: number

    CoverageReport:
      type: object
      required:
        - overall_percentage
        - critical_modules
      properties:
        overall_percentage:
          type: number
          minimum: 0
          maximum: 100
        critical_modules:
          type: object
          additionalProperties:
            type: number
            minimum: 0
            maximum: 100

    PerformanceMetrics:
      type: object
      properties:
        test_execution_time:
          type: number
        baseline_time:
          type: number
        time_increase_factor:
          type: number

    QualityGateResult:
      type: object
      required:
        - build_id
        - overall_status
        - gates
        - can_merge
      properties:
        build_id:
          type: string
        overall_status:
          type: string
          enum: [PASS, FAIL, WARNING]
        can_merge:
          type: boolean
        gates:
          type: array
          items:
            type: object
            properties:
              gate_type:
                type: string
                enum: [TEST_PASS, COVERAGE_OVERALL, COVERAGE_CRITICAL, PERFORMANCE, LINT]
              status:
                type: string
                enum: [PASS, FAIL, WARNING]
              message:
                type: string
              actual_value:
                type: number
              expected_value:
                type: number
        timestamp:
          type: string
          format: date-time