# Minimal profile template for RAG Quick Start
# Extends base template with minimal configuration for 50 documents

version: '3.8'

services:
  iris:
    environment:
      - ISC_PASSWORD=${ISC_PASSWORD:-SYS}
      - ISC_DATA_DIRECTORY=/opt/irisapp/data
      - IRIS_MINIMAL_MODE=true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  rag_app:
    environment:
      - IRIS_HOST=iris
      - IRIS_PORT=1972
      - IRIS_USERNAME=${IRIS_USERNAME:-demo}
      - IRIS_PASSWORD=${IRIS_PASSWORD:-demo}
      - IRIS_NAMESPACE=${IRIS_NAMESPACE:-USER}
      - PYTHONPATH=/app
      - BATCH_SIZE=${BATCH_SIZE:-16}
      - MAX_WORKERS=${MAX_WORKERS:-2}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - DOCUMENT_LIMIT=50
      - PROFILE=minimal
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  iris_data:
    driver: local
  rag_data:
    driver: local

networks:
  rag_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16