# Standard profile template for RAG Quick Start
# Extends base template with MCP server for 500 documents

version: '3.8'

services:
  iris:
    environment:
      - ISC_PASSWORD=${ISC_PASSWORD:-SYS}
      - ISC_DATA_DIRECTORY=/opt/irisapp/data
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  rag_app:
    environment:
      - IRIS_HOST=iris
      - IRIS_PORT=1972
      - IRIS_USERNAME=${IRIS_USERNAME:-demo}
      - IRIS_PASSWORD=${IRIS_PASSWORD:-demo}
      - IRIS_NAMESPACE=${IRIS_NAMESPACE:-USER}
      - PYTHONPATH=/app
      - BATCH_SIZE=${BATCH_SIZE:-32}
      - MAX_WORKERS=${MAX_WORKERS:-4}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - DOCUMENT_LIMIT=500
      - PROFILE=standard
      - MCP_SERVER_URL=http://mcp_server:3000
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  mcp_server:
    image: ${MCP_IMAGE:-node:18-alpine}
    container_name: rag_mcp_server
    ports:
      - "${MCP_PORT:-3000}:3000"
    working_dir: /app
    command: ["npm", "start"]
    volumes:
      - ./nodejs:/app
    environment:
      - NODE_ENV=production
      - RAG_API_URL=http://rag_app:8000
      - IRIS_HOST=iris
      - IRIS_PORT=1972
    depends_on:
      iris:
        condition: service_healthy
      rag_app:
        condition: service_healthy
    networks:
      - rag_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  iris_data:
    driver: local
  rag_data:
    driver: local

networks:
  rag_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16