# Example Testing Configuration for rag-templates
#
# CONSTITUTIONAL REQUIREMENT: All tests MUST execute against live IRIS database
# Mock mode violates Section III of the project constitution

global:
  default_timeout: 300
  max_memory_mb: 1024
  mock_llm: false  # Constitutional requirement: use live database
  report_format: ["markdown", "json"]
  require_iris_database: true  # Constitutional enforcement

# Example-specific configurations
examples:
  "basic/try_basic_rag_pipeline.py":
    timeout: 180
    expected_outputs: ["answer", "sources"]
    test_queries:
      - "What is diabetes?"
      - "How does insulin work?"
    performance_bounds:
      max_execution_time: 120
      max_memory_mb: 512
    validation_rules:
      answer_min_length: 50
      answer_max_length: 1500
      sources_min_count: 1
      sources_max_count: 10

  "basic/try_hybrid_graphrag_pipeline.py":
    timeout: 300
    optional_dependencies: ["iris-vector-graph"]
    graceful_fallback: true
    expected_outputs: ["answer", "sources", "metadata"]
    test_queries:
      - "What medications treat diabetes?"
      - "How do cancer treatments work?"
    performance_bounds:
      max_execution_time: 240
      max_memory_mb: 768
    features: ["hybrid_search", "graph_traversal"]

  "crag/try_crag_pipeline.py":
    timeout: 240
    expected_outputs: ["answer", "sources", "relevance_score"]
    test_queries:
      - "What are the symptoms of diabetes?"
      - "How does chemotherapy work?"
    performance_bounds:
      max_execution_time: 180
      max_memory_mb: 640
    features: ["relevance_evaluation", "corrective_generation"]

  "reranking/try_basic_rerank.py":
    timeout: 200
    expected_outputs: ["answer", "sources", "rerank_scores"]
    test_queries:
      - "What causes heart disease?"
      - "How do vaccines work?"
    performance_bounds:
      max_execution_time: 150
      max_memory_mb: 512
    features: ["rerank"]

  "demo_graph_visualization.py":
    timeout: 600
    expected_files:
      - "graph_visualization.html"
      - "graph_data.json"
    expected_outputs: ["visualization_stats", "generated_files"]
    performance_bounds:
      max_execution_time: 300
      max_memory_mb: 1024
    interactive: true
    features: ["visualization", "graph_export"]

  "demo_ontology_support.py":
    timeout: 400
    expected_outputs: ["ontology_stats", "entity_mapping"]
    performance_bounds:
      max_execution_time: 250
      max_memory_mb: 768
    features: ["ontology", "entity_extraction"]

# Global validation rules
validation:
  answer:
    min_length: 20
    max_length: 2000
    required_keywords: []
    avoid_keywords: ["dummy", "mock", "test response"]

  sources:
    min_count: 1
    max_count: 20
    required_fields: ["content"]
    optional_fields: ["metadata", "score"]

  performance:
    max_execution_time: 300
    max_memory_mb: 1024
    max_cpu_percent: 80

  graph_data:
    min_nodes: 1
    min_edges: 0
    required_node_fields: ["id"]
    required_edge_fields: ["source", "target"]

# Test data configuration
test_data:
  mock_responses:
    diabetes: "Diabetes is a chronic condition affecting blood sugar regulation..."
    insulin: "Insulin is a hormone that regulates glucose metabolism..."
    cancer: "Cancer involves abnormal cell growth and division..."

  sample_queries:
    medical:
      - "What is diabetes?"
      - "How does insulin work?"
      - "What causes cancer?"
      - "How do vaccines work?"

    complex:
      - "What is the relationship between insulin resistance and type 2 diabetes?"
      - "How do different cancer treatments compare in effectiveness?"
      - "What are the long-term effects of uncontrolled diabetes?"

    comparative:
      - "What are the differences between type 1 and type 2 diabetes?"
      - "How do chemotherapy and immunotherapy differ?"
      - "What distinguishes viral from bacterial infections?"

# Error handling configuration
error_handling:
  retry_on_failure: false
  capture_stack_traces: true
  timeout_grace_period: 30

  expected_errors:
    missing_dependencies:
      patterns: ["ModuleNotFoundError", "ImportError"]
      severity: "warning"
      guidance: "Install required dependencies"

    api_errors:
      patterns: ["API key", "authentication", "rate limit"]
      severity: "warning"
      guidance: "Check API configuration"

    database_errors:
      patterns: ["connection", "database", "SQL"]
      severity: "error"
      guidance: "Check database connectivity"

# Reporting configuration
reporting:
  include_performance_graphs: false
  include_detailed_logs: true
  include_error_analysis: true
  include_validation_details: true

  output_formats:
    - markdown
    - json

  summary_metrics:
    - success_rate
    - average_execution_time
    - average_memory_usage
    - validation_scores

# CI/CD integration settings
ci_integration:
  fail_on_example_failure: true
  fail_on_validation_score_below: 0.7
  generate_artifacts: true
  upload_reports: false

# Development settings
development:
  verbose_output: true
  debug_mode: false
  save_intermediate_results: true
  parallel_execution: false